
version: 2
sources: 
    - name: CUST_DATA_M
      database: "{{( 'VINAY' )}}"
      schema: GHAC_STAGE
      tables:
        - name: customers
        - name: customer_financials
        - name: stg_customers_snap
        - name: stg_customers_snap_test

